### PR TITLE
Frontend env vars at container runtime

### PR DESCRIPTION
**Pull request by john-dupuy**
Address https://github.com/ibutsu/ibutsu-server/issues/192 by:
- creating a `public/settings.js` file that is loaded before react
- adding a `start-frontend.js` that overwrites the `public/settings.js` file at container runtime
- changing `src/settings.js` to be assigned to window.settings

Depends on #188

### CODE REVIEW

**Comment by rsnyman** [comment]
@john-dupuy what do you think of making an abstraction layer between the window.settings object and the code? So rather than using the object directly, use the Settings object as a wrapper/interim. It also looks cleaner :-)

```javascript
// public/settings.js
window.settings = {...};
```

```javascript
// src/settings.js
Settings = window.settings;
```

```javascript
// other code
import { Settings } from './settings';

fetch(Settings.serverUrl)
```

**Comment by john-dupuy** [comment]
> @john-dupuy what do you think of making an abstraction layer between the window.settings object and the code? So rather than using the object directly, use the Settings object as a wrapper/interim. It also looks cleaner :-)
> 
> ```js
> // public/settings.js
> window.settings = {...};
> ```
> 
> ```js
> // src/settings.js
> Settings = window.settings;
> ```
> 
> ```js
> // other code
> import { Settings } from './settings';
> 
> fetch(Settings.serverUrl)
> ```
Ah! That's basically what I had here: https://github.com/ibutsu/ibutsu-server/pull/193/commits/1b5258b1c33b482246b51ed2c97c9d501aa3c119. I must've misunderstood your request earlier. I agree it looks cleaner :) - will update.

**Comment by rsnyman** [comment]
> Ah! That's basically what I had here (minus the more apt names): [1b5258b](https://github.com/ibutsu/ibutsu-server/commit/1b5258b1c33b482246b51ed2c97c9d501aa3c119). I must've misunderstood your request earlier. I agree it looks cleaner :) - will update.

Ja, sorry, I was only half-awake when I look at it earlier ;-)

**Comment by john-dupuy** [comment]
Haha no worries - just updated keeping `Settings` in src/settings.js

**Review by rsnyman — APPROVED** [review]

**Pull request merged**
