### PR TITLE
Add a checkbox select filter for exceptions

### PR DESCRIPTION
**Pull request by john-dupuy**
#201 

* Add a checkbox select filter that will automatically filter on `metadata.exception_name in <semi-colon-list>`
* Use the result_aggregator widget to easily fetch the exceptions
* Modify result_aggregator widget so we can directly pass run_id and make `days` optional
* Add support for hiding chips in `FilterTable`
* Hide `project_id` filter chip in results/runs table

Uploading filter-by-exception.mp4…

### CODE REVIEW

**Comment by john-dupuy** [comment]
I don't know why the video isn't uploading but here's a screenshot:
Screenshot from 2021-09-14 13-30-07

**Comment by jjaquish** [comment]
Well LGTM. I ran this locally and it seems to work without issue from my testing.

**Review by jjaquish — COMMENTED** [review]
Oops, meant this to be a review. See comment above. tl;dr ran it and it works and LGTM

**Review by mshriver — APPROVED** [review]
Pulled and ran locally in podman, looks good on the small scale. Thanks @john-dupuy !

**Review by rsnyman — APPROVED** [review]

**Pull request merged**
