### PR TITLE
Upgrade celery to handle a security issue, let's see if this works

### PR DESCRIPTION
**Pull request by rsnyman**
We previously pinned Celery due to a bug in Kombu. Many moons have gone by since the advent of this bug and subsequent pin. Let us see if the bug still exists.

### CODE REVIEW

**Review by john-dupuy — CHANGES_REQUESTED** [review]
Trying to start the celery worker locally with a command like:
```
celery worker -E -A ibutsu_server.tasks.queues:app --concurrency 1 --loglevel info
```
I get an error:
```
You are using `-A` as an option of the worker sub-command:
celery worker -A celeryapp <...>

The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp worker <...>
```

So it sounds like we'll need to update our `Dockerfile.worker`?

**Comment by john-dupuy** [comment]
Changing the `-A <app>` part to be after `celery` fixed up worker/scheduler, both appear to be working fine locally after that.

**Comment by john-dupuy** [comment]
I think these two lines will also need updating - https://github.com/ibutsu/ibutsu-server/blob/master/backend/docker/Dockerfile.scheduler#L16 and https://github.com/ibutsu/ibutsu-server/blob/master/backend/docker/Dockerfile.worker#L15

**Review by john-dupuy — APPROVED** [review]

**Comment by rsnyman** [comment]
Thanks @john-dupuy you're a legend! Hope you're doing well!

**Comment by john-dupuy** [comment]
No problem! Hope you and the team are doing great too! :smiley: :

**Pull request merged**
